Descriptions:
  name: base_segmentation
  version: v1.0
  date: "20211125"

Global:
  work_dir: /home/liuxin/Documents/CVMI_Sementic_Segmentation/log/deeplab
  log:
    log_level: INFO
  log_config:
    interval: 5
    hooks: [{name: TensorboardLoggerHook, by_epoch: False}]
  checkpoint_config:
    interval: 1
    by_epoch: true
  workflow: 
    - [train, 5]
    - [val, 1]
  distributed: true
  gpus: 1
  batch_size: 32
  num_workers: 4
  max_epoch: 600
  optimizer: 
    name: SGD
    lr: 0.005
    momentum: 0.9
    weight_decay: 5.0e-4
  optimizer_config:
  lr_config: 
    policy: fixed



Data:
  name: skmt
  dataset_root: /home/liuxin/Documents/CVMI_Sementic_Segmentation/data/dataset/SKMT/Seg
  num_classes: &num_classes 11
  image_size: &image_size 256
  type: rgb
  transforms:
    train:
      RandomHorizontalFlip: 
      RandomScaleCrop:
        base_size: *image_size
        crop_size: *image_size
      FixScaleCrop:
        crop_size: *image_size
      RandomRotate:
        - 10
      RandomGaussianBlur:
      Normalize:
        - [0.485, 0.456, 0.406]
        - [0.229, 0.224, 0.225]
      ToTensor:
    val:
      FixScaleCrop:
        crop_size: *image_size
      Normalize:
        - [0.485, 0.456, 0.406]
        - [0.229, 0.224, 0.225]
      ToTensor:

Evaluator:
  name: BaseEvaluator
  num_classes: *num_classes
  evaluate_list:
    - overall_acc
    - mIou
    - mDice

# config network and losses
Model:
  root_path: /home/liuxin/Documents/CVMI_Sementic_Segmentation/configs
  sync_BN: true
  backbone:
    name: resnet50
    output_stride: 32
  neck:
    name: Identity
  decode_heads:
    trunk_seg_head:
      name: Unet
      in_channels: 2048
      num_classes: *num_classes
      factors: [2, 2, 4, 2]
      criterion: 
        name: ImageBasedCrossEntropy2D
  match_block:
    image_size: *image_size
    type: "bilinear"


  




