Descriptions:
  name: base_segmentation
  version: v1.0

Global:
  log_path: /home/liuxin/Documents/CVMI_Sementic_Segmentation/log/base_demo
  distributed: false
  gpus: 1
  batch_size: 100
  learning_rate: 1e-5
  optimizer: 
    name: SGD
    lr: 0.00125
    momentum: 0.9
    weight_decay: 0.0001
  lr_config: 
    policy: poly
    power: 0.9
    min_lr: 1e-4
    by_epoch: false
  max_epoch: 30

Data:
  name: skmt
  dataset_root: /home/liuxin/Documents/CVMI_Sementic_Segmentation/data/dataset/SKMT/Seg
  num_classes: &num_classes 11
  image_size: &image_size 256
  type: rgb
  transforms:
    train:
      RandomHorizontalFlip: 
      RandomScaleCrop:
        base_size: *image_size
        crop_size: *image_size
      FixScaleCrop:
        crop_size: *image_size
      RandomRotate:
        - 10
      RandomGaussianBlur:
      Normalize:
        - [0.485, 0.456, 0.406]
        - [0.229, 0.224, 0.225]
      ToTensor:
    val:
      FixScaleCrop:
        crop_size: *image_size
      Normalize:
        - [0.485, 0.456, 0.406]
        - [0.229, 0.224, 0.225]
      ToTensor:


# config network and losses
Model:
  root_path: /home/liuxin/Documents/CVMI_Sementic_Segmentation/configs
  sync_BN: true
  backbone:
    name: resnet50
    output_stride: 32
  neck:
    name: Identity
  decode_head:
    name: Unet
    in_channel: 2048
    num_classes: *num_classes
    factors: [2, 2, 4, 2]
  match_block:
    image_size: *image_size
    type: "bilinear"

Criterion:
  name: ImageBasedCrossEntropy2D




